### PR TITLE
 Switch from TravisCI to GitHub Actions

### PR DESCRIPTION
**Pull request by mlocati**
PS: this PR includes the changes in #206

### CODE REVIEW

**Comment by mlocati** [comment]
We have to get rid of travis-ci.com because of this:

immagine

**Comment by ashnazg** [comment]
These builds run on travis-ci.org rather than .com, don't they?

**Comment by mlocati** [comment]
> These builds run on travis-ci.org rather than .com, don't they?

@ashnazg 

immagine

**Comment by pierrejoye** [comment]
Looks good, thanks!

The fails are not related to this PR at all, and moving away from Travis sounds like a very good plan!

**Pull request merged**
