### PR TITLE
travis: hhvm and hhvm nightly added

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by stof** [comment]
Looks like atoum is not compatible with HHVM, making this useless.

and the Behat suite does not seem to take HHVM into account either

**Comment by jubianchi** [comment]
@stof you are right, atoum does not work with HHVM yet. I'll have to see how I can fix the issues...

**Comment by stof** [comment]
Well, I only see 2 choices:

- make Atoum work on HHVM
- switch to a different test tool for the Pickle testsuite

Otherwise, we won't have any chance to make the testsuite run on HHVM (and merging this PR would only waste Travis resources).

**Comment by jubianchi** [comment]
@stof no need to be so radical.

> make Atoum work on HHVM

I can work on this but not in the coming days. Any help is appreciated.

> switch to a different test tool for the Pickle testsuite

You rewrite the testsuite ?

> merging this PR would only waste Travis resources

I think Travis has enough resource to run everything we ask him to run, even if it's just to gather failures.

**Comment by stof** [comment]
@jubianchi Travis only allows you to run 5 jobs in parallel per repo owner. So adding 2 jobs per build which cannot provide any meaningful output (except that Atoum still does not support HHVM, which is not the job of Pickle) means we are wasting the resources that Travis allocates to FriendsOfPHP, slowing down all other builds to wait for this known failure.

**Comment by pborreli** [comment]
@stof we could just wait to merge this PR until it is relevant (when atoum is fixed)

**Comment by TomasVotruba** [comment]
> @stof ...wasting the resources that Travis allocates to FriendsOfPHP, slowing down all other builds to wait for this known failure

Sounds interesting. Are there some info about how Travis allocates/prioritize it's sources?

**Comment by stof** [comment]
@TomasVotruba which sources are you talking about ?

**Comment by TomasVotruba** [comment]
@stof Any you know about. Where do have this information from?

**Comment by stof** [comment]
@TomasVotruba The Travis team gave me this information on Twitter a few months ago when I asked (and from what I saw today with builds in the Doctrine org, they haven't changed the threshold. It is still 5).

They are limiting the number of concurrent jobs per github user/org so that a repo with a huge matrix (doctrine/dbal for instance) cannot make all other projects wait for available workers.

Note that for Travis Pro, you have the same kind of limit on the number of concurrent jobs, but the threshold depend on your plan.

**Comment by TomasVotruba** [comment]
@stof Thanks a lot for sharing! Good to know while working with Travis matrix.

**Comment by stof** [comment]
@TomasVotruba this is one of the reason why I generally avoid testing older versions of dependencies on all PHP versions but rather include a few specific jobs in the matrix: https://github.com/Behat/MinkExtension/pull/128

**Comment by TomasVotruba** [comment]
@stof Neat trick

**Comment by pierrejoye** [comment]
any progress here?

**Comment by TomasVotruba** [comment]
@pierrejoye Done from my part. Or are there any request for change?

**Comment by pierrejoye** [comment]
@jubianchi does atoum support hhvm now?

**Comment by jubianchi** [comment]
I ran the unit test suite on my laptop with the HHVM branch of atoum and everything is green. We are working on the branch to merge it in the master and tag a new release ;)

**Comment by pierrejoye** [comment]
I merge it, we can update atoum when @jubianchi  is ready :)
PR--;

**Pull request merged**
