### PR TITLE
Fix almost all tests

### PR DESCRIPTION
**Pull request by endelwar**
This PR includes:
- fix strings in tests to respect command output
- bump composer dependency to 1.6
- lowercase compare of version so that 2.2.0-rc1 == 2.2.0-RC1
- permit extension download via insecure protocol like git:// or http://
- add php 7.1, 7.2, 7.3, 7.4 (snapshot) and nightly to Travis config

### CODE REVIEW

**Comment by torinaki** [comment]
@endelwar could you please update on your progress on this PR? Would you continue to finalize it?

**Comment by endelwar** [comment]
@torinaki I was waiting for feedback from the maintainers about this PR (I had forgot about this PR in the meantime).

@weltling @Hywan what do you think? Is this PR mergeable or needs some refinement?

**Comment by pierrejoye** [comment]
something is wrong in the travis environment setup, Environment variables are not set. It seems to be reason why your PR fails.

**Comment by Hywan** [comment]
After a quicklook: The PR looks good to me. Please, make sure Travis reports a green check :-).

**Comment by endelwar** [comment]
@Hywan thanks for the feedback. Making Travis green is quite an effort, looking at travis build 425:
- tests on php 5.4-7.1 has failure on the process of downloading beta release of extension, I think that it is material for another PR
- tests on php 7.2 needs https://github.com/hoaproject/Realdom/pull/25 implemented and a new release of https://github.com/hoaproject/Realdom has to be done and (finally) composer.json need a version bump on this package
- also on php 7.2 travis environment has more extensions already installed by default compared to the other environments, which make installation tests fail
- on HHVM atoum has method signature issues and [as of July 2017 it doesn't support HHVM](https://github.com/atoum/atoum/issues/624), does Pickle want to support HHVM?

I'm going to push another change to this PR (adding php 7.3) to see if something has changed in these 10 months in travis php build images on the default installed extensions front

**Comment by Hywan** [comment]
I can take care of that. My agenda is overfull, but I can take a look at it.

**Comment by pierrejoye** [comment]
Tests are green now on travis and a few machines I tried. 

Thanks for your effort!

**Pull request closed without merging**
